### ISSUE TITLE
Write a brief introduction to T-Rover

### ISSUE THREAD

**Issue by jamestharpe** [tmobile/t-rover#1]
It's difficult to tell what the T-Rover project is all about. A brief introduction in the readme would be very helpful.

For example:

> T-Rover is a DIY self-driving radio controlled car intended as a basic introduction to machine learning. The parts should cost about $___ and the build can be completed in about ___ to ___ days in most cases.

**Comment by jimjsong** [comment]
thanks.  wrote something up.  PLEASE feel free to make recommendations.

**Comment by jamestharpe** [comment]
LGTM :)
